import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
      <title>ClueLess</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <p className='flex justify-center items-center h-screen text-6xl font-bold'>This is going to be ClueLess Admin Dashboard</p>
    </div>
  )
}

export default Home
